
import { Client, ServiceResponse } from '@/types';
import { supabase } from '@/integrations/supabase/client';
import { mapDbClientToApp, mapAppClientToDb } from '@/integrations/supabase/mappers';

export async function fetchClientsFromApi(): Promise<Client[]> {
  const { data, error } = await supabase
    .from('clientes')
    .select('*')
    .order('nome', { ascending: true });
  
  if (error) {
    console.error("Error fetching clients:", error);
    throw error;
  }

  if (!data || !Array.isArray(data)) {
    console.warn("Data from API is not an array or is null:", data);
    return [];
  }

  return data.map(mapDbClientToApp);
}

export async function createClientInApi(clientData: Partial<Client>): Promise<ServiceResponse<Client>> {
  if (!clientData.name || !clientData.phone) {
    throw new Error('Nome e telefone são obrigatórios');
  }
  
  const dataToInsert = mapAppClientToDb({
    id: '', // This will be generated by Supabase
    name: clientData.name,
    phone: clientData.phone,
    email: clientData.email,
    notes: clientData.notes,
    birthdate: clientData.birthdate,
    totalSpent: clientData.totalSpent || 0,
    lastAppointment: clientData.lastAppointment,
    createdAt: new Date().toISOString()
  });
  
  // Remove id as it will be generated by Supabase
  delete dataToInsert.id;
  
  try {
    console.log("Attempting to insert client data:", dataToInsert);
    
    const { data, error } = await supabase
      .from('clientes')
      .insert(dataToInsert)
      .select('*')
      .single();
      
    if (error) {
      console.error('Error creating client:', error);
      return { error: error.message };
    }
    
    if (!data) {
      console.error('No data returned after client creation');
      return { error: 'Falha ao criar cliente: Nenhum dado retornado' };
    }
    
    console.log("Client successfully created:", data);
    const newClient = mapDbClientToApp(data);
    return { data: newClient };
  } catch (err: any) {
    console.error('Unexpected error creating client:', err);
    return { error: err.message || 'Erro inesperado ao criar cliente' };
  }
}

export async function updateClientInApi(clientId: string, clientData: Partial<Client>): Promise<ServiceResponse<Client>> {
  const updateData = mapAppClientToDb({
    id: clientId,
    name: clientData.name,
    phone: clientData.phone,
    email: clientData.email,
    notes: clientData.notes,
    birthdate: clientData.birthdate,
    totalSpent: clientData.totalSpent,
    lastAppointment: clientData.lastAppointment,
    createdAt: ''
  });
  
  // Remove the id from update data
  delete updateData.id;
  
  const { data, error } = await supabase
    .from('clientes')
    .update(updateData)
    .eq('id', clientId)
    .select('*')
    .single();
    
  if (error) {
    return { error: error.message };
  }
  
  if (data) {
    const updatedClient = mapDbClientToApp(data);
    return { data: updatedClient };
  }
  
  return { error: 'Falha ao atualizar cliente' };
}

export async function deleteClientInApi(clientId: string): Promise<ServiceResponse<boolean>> {
  const { error } = await supabase
    .from('clientes')
    .delete()
    .eq('id', clientId);
    
  if (error) {
    return { error: error.message };
  }
  
  return { data: true };
}
